"""Add Knowledge Engine models

Revision ID: 421139be736d
Revises: ca71b6cd625d
Create Date: 2026-08-05 03:29:54.545166
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "421139be736d"
down_revision: str | Sequence[str] | None = "ca71b6cd625d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "global_knowledge",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pattern_name", sa.String(length=80), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("total_occurrences", sa.Integer(), nullable=False),
        sa.Column("success_count", sa.Integer(), nullable=False),
        sa.Column("failure_count", sa.Integer(), nullable=False),
        sa.Column("neutral_count", sa.Integer(), nullable=False),
        sa.Column("historical_confidence", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("validation_window", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_global_knowledge")),
        sa.UniqueConstraint(
            "pattern_name", "validation_window", name="uq_global_knowledge_pattern_window"
        ),
    )
    op.create_table(
        "token_hypotheses",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("token_id", sa.String(length=36), nullable=False),
        sa.Column("hypothesis_type", sa.String(length=80), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=2), nullable=False),
        sa.Column("rule_version", sa.String(length=32), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("caused_by", sa.JSON(), nullable=False),
        sa.Column("caused_by_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["token_id"],
            ["tokens.id"],
            name=op.f("fk_token_hypotheses_token_id_tokens"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_token_hypotheses")),
        sa.UniqueConstraint(
            "token_id",
            "hypothesis_type",
            "rule_version",
            "caused_by_hash",
            name="uq_token_hypotheses_idempotency",
        ),
    )
    with op.batch_alter_table("token_hypotheses", schema=None) as batch_op:
        batch_op.create_index(
            "ix_hypotheses_token_created", ["token_id", "created_at"], unique=False
        )
        batch_op.create_index(
            "ix_hypotheses_type_created", ["hypothesis_type", "created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_token_hypotheses_token_id"), ["token_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("token_hypotheses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_token_hypotheses_token_id"))
        batch_op.drop_index("ix_hypotheses_type_created")
        batch_op.drop_index("ix_hypotheses_token_created")

    op.drop_table("token_hypotheses")
    op.drop_table("global_knowledge")
    # ### end Alembic commands ###
