"""add virtual portfolio

Revision ID: 534ff548f3d4
Revises: c83fedd0c804
Create Date: 2026-08-06 20:03:33.942021
"""

from collections.abc import Sequence

revision: str = "534ff548f3d4"
down_revision: str | Sequence[str] | None = "c83fedd0c804"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
