"""Add event signal knowledge models

Revision ID: a3f3998a6ece
Revises: 20260804_0001
Create Date: 2026-08-05 02:00:55.567376
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a3f3998a6ece"
down_revision: str | Sequence[str] | None = "20260804_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "token_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("token_id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("caused_by", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["token_id"],
            ["tokens.id"],
            name=op.f("fk_token_events_token_id_tokens"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_token_events")),
    )
    with op.batch_alter_table("token_events", schema=None) as batch_op:
        batch_op.create_index("ix_events_token_created", ["token_id", "created_at"], unique=False)
        batch_op.create_index("ix_events_type_created", ["event_type", "created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_token_events_token_id"), ["token_id"], unique=False)

    op.create_table(
        "token_knowledge",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("token_id", sa.String(length=36), nullable=False),
        sa.Column("pattern_name", sa.String(length=80), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("historical_occurrences", sa.Integer(), nullable=True),
        sa.Column("historical_confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("caused_by", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["token_id"],
            ["tokens.id"],
            name=op.f("fk_token_knowledge_token_id_tokens"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_token_knowledge")),
    )
    with op.batch_alter_table("token_knowledge", schema=None) as batch_op:
        batch_op.create_index(
            "ix_knowledge_token_created", ["token_id", "created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_token_knowledge_token_id"), ["token_id"], unique=False)

    op.create_table(
        "token_signals",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("token_id", sa.String(length=36), nullable=False),
        sa.Column("signal_type", sa.String(length=80), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("caused_by", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["token_id"],
            ["tokens.id"],
            name=op.f("fk_token_signals_token_id_tokens"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_token_signals")),
    )
    with op.batch_alter_table("token_signals", schema=None) as batch_op:
        batch_op.create_index("ix_signals_token_created", ["token_id", "created_at"], unique=False)
        batch_op.create_index(
            "ix_signals_type_created", ["signal_type", "created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_token_signals_token_id"), ["token_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("token_signals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_token_signals_token_id"))
        batch_op.drop_index("ix_signals_type_created")
        batch_op.drop_index("ix_signals_token_created")

    op.drop_table("token_signals")
    with op.batch_alter_table("token_knowledge", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_token_knowledge_token_id"))
        batch_op.drop_index("ix_knowledge_token_created")

    op.drop_table("token_knowledge")
    with op.batch_alter_table("token_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_token_events_token_id"))
        batch_op.drop_index("ix_events_type_created")
        batch_op.drop_index("ix_events_token_created")

    op.drop_table("token_events")
    # ### end Alembic commands ###
