"""add_token_alert_confidence_level

Revision ID: c83fedd0c804
Revises: 783b1c238e02
Create Date: 2026-08-06 04:44:33.164627
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c83fedd0c804"
down_revision: str | Sequence[str] | None = "783b1c238e02"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("token_alerts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("confidence_level", sa.String(length=64), nullable=True))

    with op.batch_alter_table("token_truths", schema=None) as batch_op:
        batch_op.create_index("ix_truths_status_created", ["status", "created_at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("token_truths", schema=None) as batch_op:
        batch_op.drop_index("ix_truths_status_created")

    with op.batch_alter_table("token_alerts", schema=None) as batch_op:
        batch_op.drop_column("confidence_level")

    # ### end Alembic commands ###
