"""Add caused_by_hash and idempotency constraints

Revision ID: cc08cc58355e
Revises: 61fa9384fdb0
Create Date: 2026-08-05 02:15:52.398146
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "cc08cc58355e"
down_revision: str | Sequence[str] | None = "61fa9384fdb0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("token_events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("caused_by_hash", sa.String(length=64), nullable=False))
        batch_op.create_unique_constraint(
            "uq_token_events_idempotency",
            ["token_id", "event_type", "rule_version", "caused_by_hash"],
        )

    with op.batch_alter_table("token_signals", schema=None) as batch_op:
        batch_op.add_column(sa.Column("caused_by_hash", sa.String(length=64), nullable=False))
        batch_op.create_unique_constraint(
            "uq_token_signals_idempotency",
            ["token_id", "signal_type", "rule_version", "caused_by_hash"],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("token_signals", schema=None) as batch_op:
        batch_op.drop_constraint("uq_token_signals_idempotency", type_="unique")
        batch_op.drop_column("caused_by_hash")

    with op.batch_alter_table("token_events", schema=None) as batch_op:
        batch_op.drop_constraint("uq_token_events_idempotency", type_="unique")
        batch_op.drop_column("caused_by_hash")

    # ### end Alembic commands ###
