"""Add strength confidence and rule versions

Revision ID: 61fa9384fdb0
Revises: a3f3998a6ece
Create Date: 2026-08-05 02:08:34.432117
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '61fa9384fdb0'
down_revision: str | Sequence[str] | None = 'a3f3998a6ece'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rule_version', sa.String(length=32), nullable=False))

    with op.batch_alter_table('token_signals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strength', sa.Numeric(precision=4, scale=2), nullable=False))
        batch_op.add_column(sa.Column('confidence', sa.Numeric(precision=4, scale=2), nullable=False))
        batch_op.add_column(sa.Column('rule_version', sa.String(length=32), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_signals', schema=None) as batch_op:
        batch_op.drop_column('rule_version')
        batch_op.drop_column('confidence')
        batch_op.drop_column('strength')

    with op.batch_alter_table('token_events', schema=None) as batch_op:
        batch_op.drop_column('rule_version')

    # ### end Alembic commands ###

