"""add_truths_status_created_index

Revision ID: 783b1c238e02
Revises: e398a6ae4278
Create Date: 2026-08-05 17:37:50.576491
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '783b1c238e02'
down_revision: Union[str, Sequence[str], None] = 'e398a6ae4278'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_truths', schema=None) as batch_op:
        batch_op.create_index('ix_truths_status_created', ['status', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_truths', schema=None) as batch_op:
        batch_op.drop_index('ix_truths_status_created')

    # ### end Alembic commands ###

