"""add alert models

Revision ID: ca71b6cd625d
Revises: cc08cc58355e
Create Date: 2026-08-05 02:28:19.485651
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

revision: str = 'ca71b6cd625d'
down_revision: str | Sequence[str] | None = 'cc08cc58355e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('token_id', sa.String(length=36), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('source_kind', sa.String(length=20), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('minimum_strength', sa.Float(), nullable=True),
    sa.Column('minimum_confidence', sa.Float(), nullable=True),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('rule_version', sa.String(length=20), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], name=op.f('fk_alert_rules_token_id_tokens')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_rules'))
    )
    op.create_table('token_alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=36), nullable=False),
    sa.Column('token_id', sa.String(length=36), nullable=False),
    sa.Column('source_kind', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('severity', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deduplication_key', sa.String(length=64), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], name=op.f('fk_token_alerts_rule_id_alert_rules')),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], name=op.f('fk_token_alerts_token_id_tokens')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_token_alerts')),
    sa.UniqueConstraint('deduplication_key', name='uq_token_alert_dedup')
    )
    op.create_table('notification_deliveries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('alert_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['token_alerts.id'], name=op.f('fk_notification_deliveries_alert_id_token_alerts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_deliveries'))
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payload_json', sa.JSON(), nullable=True))
        batch_op.alter_column('deduplication_key',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_alerts_created_at'))
        batch_op.drop_index(batch_op.f('ix_alerts_dedupe_created'))
        batch_op.drop_index(batch_op.f('ix_alerts_token_created'))
        batch_op.create_unique_constraint('uq_alert_dedup', ['deduplication_key', 'is_demo'])
        batch_op.drop_column('payload')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payload', sqlite.JSON(), nullable=False))
        batch_op.drop_constraint('uq_alert_dedup', type_='unique')
        batch_op.create_index(batch_op.f('ix_alerts_token_created'), ['token_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_dedupe_created'), ['deduplication_key', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_created_at'), ['created_at'], unique=False)
        batch_op.alter_column('deduplication_key',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('payload_json')

    op.drop_table('notification_deliveries')
    op.drop_table('token_alerts')
    op.drop_table('alert_rules')
    # ### end Alembic commands ###

