"""Add TokenTruth and GlobalKnowledge Context

Revision ID: e398a6ae4278
Revises: 421139be736d
Create Date: 2026-08-05 03:47:21.257881
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'e398a6ae4278'
down_revision: str | Sequence[str] | None = '421139be736d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_truths',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('token_id', sa.String(length=36), nullable=False),
    sa.Column('hypothesis_id', sa.String(length=36), nullable=False),
    sa.Column('expected_outcome', sa.JSON(), nullable=False),
    sa.Column('observed_outcome', sa.JSON(), nullable=False),
    sa.Column('gain', sa.Float(), nullable=True),
    sa.Column('loss', sa.Float(), nullable=True),
    sa.Column('accuracy_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['token_hypotheses.id'], name=op.f('fk_token_truths_hypothesis_id_token_hypotheses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], name=op.f('fk_token_truths_token_id_tokens'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_token_truths')),
    sa.UniqueConstraint('hypothesis_id', name='uq_token_truths_hypothesis')
    )
    with op.batch_alter_table('token_truths', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_truths_hypothesis_id'), ['hypothesis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_token_truths_token_id'), ['token_id'], unique=False)
        batch_op.create_index('ix_truths_token_created', ['token_id', 'created_at'], unique=False)

    with op.batch_alter_table('global_knowledge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('market_regime', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('chain', sa.String(length=32), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_global_knowledge_pattern_window'), type_='unique')
        batch_op.create_unique_constraint('uq_global_knowledge_context', ['pattern_name', 'validation_window', 'market_regime', 'chain'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_knowledge', schema=None) as batch_op:
        batch_op.drop_constraint('uq_global_knowledge_context', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_global_knowledge_pattern_window'), ['pattern_name', 'validation_window'])
        batch_op.drop_column('chain')
        batch_op.drop_column('market_regime')

    with op.batch_alter_table('token_truths', schema=None) as batch_op:
        batch_op.drop_index('ix_truths_token_created')
        batch_op.drop_index(batch_op.f('ix_token_truths_token_id'))
        batch_op.drop_index(batch_op.f('ix_token_truths_hypothesis_id'))

    op.drop_table('token_truths')
    # ### end Alembic commands ###

