'use client';

import React,{useState}from'react';
import{CLI_COMMANDS,EVOPRO_CONFIG}from'@/data/evopro';
import{useEvoProPublic}from'../EvoProPublicContext';
import{BookOpen,Search,Copy,Check,Terminal,ChevronDown,ChevronUp}from'lucide-react';

export function CliReference(){
  const publicState=useEvoProPublic();const version=publicState?.manifest.version||EVOPRO_CONFIG.version;
  const[q,setQ]=useState('');const[cat,setCat]=useState('all');const[open,setOpen]=useState<string|null>(null);const[copied,setCopied]=useState<string|null>(null);
  const categories=[['all','Todos'],['bootstrap','Bootstrap'],['lifecycle','Lifecycle'],['goal_sprint','Goals & Sprints'],['verification','Verification'],['runtime','Runtime'],['intelligence','Cognition & Context'],['audit','Audit']];
  const rows=CLI_COMMANDS.filter(c=>(cat==='all'||c.category===cat)&&(c.command+' '+c.description).toLowerCase().includes(q.toLowerCase()));
  const copy=(s:string,e:React.MouseEvent)=>{e.stopPropagation();navigator.clipboard.writeText(s);setCopied(s);setTimeout(()=>setCopied(null),1600)};
  return <section id="cli" className="py-20 md:py-28 border-t border-white/5 relative bg-zinc-950/40"><div className="max-w-7xl mx-auto px-4 sm:px-6">
    <div className="text-center max-w-3xl mx-auto mb-12"><div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-mono font-semibold bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 mb-4"><BookOpen className="w-3.5 h-3.5"/>ADVANCED / OPERATOR INTERFACE</div><h2 className="text-3xl sm:text-5xl font-black text-white tracking-tight mb-4">CLI Reference</h2><p className="text-zinc-400 text-sm sm:text-base leading-relaxed">A experiência normal é Agent-first. Esta referência existe para debugging, CI, automação e controlo explícito por operadores. Versão canônica carregada: <strong className="text-zinc-200">v{version}</strong>.</p></div>
    <div className="max-w-4xl mx-auto mb-8 space-y-4 font-mono"><div className="relative"><Search className="w-4 h-4 text-zinc-500 absolute left-4 top-1/2 -translate-y-1/2"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Pesquisar comando..." className="w-full bg-zinc-900/90 border border-zinc-800 rounded-2xl py-3.5 pl-11 pr-4 text-xs text-white placeholder-zinc-500 focus:outline-none"/></div><div className="flex flex-wrap gap-1.5 justify-center">{categories.map(([id,label])=><button key={id} onClick={()=>setCat(id)} className={`px-3 py-1.5 rounded-xl text-xs cursor-pointer ${cat===id?'bg-zinc-800 text-emerald-400 font-bold':'text-zinc-400 hover:bg-zinc-900'}`}>{label}</button>)}</div></div>
    <div className="max-w-4xl mx-auto space-y-3 font-mono">{rows.map(cmd=>{const expanded=open===cmd.command;return <div key={cmd.command} className="rounded-2xl bg-zinc-950 border border-zinc-800 overflow-hidden"><div role="button" tabIndex={0} onClick={()=>setOpen(expanded?null:cmd.command)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setOpen(expanded?null:cmd.command)}}} className="p-4 flex items-center justify-between hover:bg-zinc-900/40 cursor-pointer"><div className="flex gap-3 items-center"><Terminal className="w-4 h-4 text-emerald-400"/><div><div className="text-xs sm:text-sm font-bold text-white">{cmd.command}</div><span className="text-[11px] text-zinc-400 font-sans">{cmd.description}</span></div></div><div className="flex items-center gap-3"><button onClick={e=>copy(cmd.command,e)} className="p-1.5 rounded-lg bg-zinc-900 text-zinc-400">{copied===cmd.command?<Check className="w-3.5 h-3.5 text-emerald-400"/>:<Copy className="w-3.5 h-3.5"/>}</button>{expanded?<ChevronUp className="w-4 h-4 text-zinc-500"/>:<ChevronDown className="w-4 h-4 text-zinc-500"/>}</div></div>{expanded&&<div className="p-4 bg-zinc-900/50 border-t border-zinc-800 text-xs text-zinc-400"><p><strong className="text-zinc-200">Uso:</strong> interface explícita para operador. Em sessões normais de IDE, o EvoPro Agent deve decidir se este comando é necessário.</p>{cmd.example&&<pre className="mt-3 p-3 bg-black rounded-xl overflow-x-auto text-emerald-300">{cmd.example}</pre>}</div>}</div>})}{rows.length===0&&<div className="text-center py-10 text-zinc-500 text-xs">Nenhum comando encontrado.</div>}</div>
  </div></section>;
}
