'use client';

import React from'react';
import{useTheme}from'@/context/ThemeContext';
import{ShieldCheck,BrainCircuit,Cpu,ArrowRight,ArrowDown}from'lucide-react';

export function DeterministicVsCognitive(){const{theme}=useTheme();const layers=[
{icon:ShieldCheck,title:'DETERMINISTIC KERNEL',tag:'STATE · INVARIANTS · GATES',copy:'Mantém estado, schemas, baselines, guardrails, Judge e invariantes verificáveis. Não deve fingir raciocínio cognitivo nem fabricar trabalho.',accent:'text-cyan-400'},
{icon:BrainCircuit,title:'EVOPRO COGNITIVE AGENT',tag:'MEMORY · CONTEXT · GOVERNANCE',copy:'Percebe o host, recupera memória, roteia contexto, mantém epistemologia, seleciona skills e decide quais ferramentas seguras são necessárias.',accent:'text-emerald-400'},
{icon:Cpu,title:'HARNESS / MODEL',tag:'REASONING · TOOLS · GENERATION',copy:'Codex, Claude Code, Antigravity ou outro harness executa raciocínio e ferramentas disponíveis. É intercambiável e não possui soberania sobre a memória ou os contratos do host.',accent:'text-purple-400'}
];return <section id="architecture" className="py-20 md:py-28 border-t border-white/5 relative"><div className="max-w-7xl mx-auto px-4 sm:px-6"><div className="text-center max-w-4xl mx-auto mb-14"><div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-mono font-semibold bg-purple-500/10 text-purple-400 border border-purple-500/20 mb-4"><Cpu className="w-3.5 h-3.5"/>SEPARATION OF POWERS</div><h2 className="text-3xl sm:text-5xl font-black text-white tracking-tight mb-4">Kernel, Agent e Harness<br/><span className="text-zinc-500">não são a mesma coisa.</span></h2><p className="text-zinc-400 text-sm sm:text-base leading-relaxed">O EvoPro preserva uma fronteira explícita entre estado determinístico, cognição operacional e capacidade do modelo. Nenhuma camada deve silenciosamente impersonar outra.</p></div>
<div className="grid lg:grid-cols-3 gap-4 items-stretch">{layers.map(({icon:Icon,title,tag,copy,accent},i)=><React.Fragment key={title}><article className="p-6 rounded-3xl bg-zinc-950 border border-zinc-800"><div className="w-11 h-11 rounded-xl bg-zinc-900 border border-zinc-800 flex items-center justify-center mb-5"><Icon className={`w-5 h-5 ${accent}`}/></div><div className="text-[10px] font-mono tracking-widest text-zinc-600 mb-2">{tag}</div><h3 className="font-black text-white mb-3">{title}</h3><p className="text-sm leading-relaxed text-zinc-400">{copy}</p></article>{i<2&&<div className="hidden lg:flex items-center justify-center -mx-3 z-10"><ArrowRight className="w-5 h-5" style={{color:theme.colors.primary}}/></div>}</React.Fragment>)}</div>
<div className="lg:hidden flex justify-center py-5"><ArrowDown className="w-4 h-4 text-zinc-700"/></div>
<div className="mt-8 rounded-2xl border border-emerald-500/15 bg-emerald-500/[.035] p-5 text-sm text-zinc-400"><strong className="text-zinc-200">Contrato:</strong> o Kernel governa estado e invariantes; o Agent governa contexto e operação cognitiva; o Harness fornece raciocínio e ferramentas. <span style={{color:theme.colors.primary}}>Autoridade humana permanece acima dos três.</span></div>
</div></section>}
