'use client';

import React from'react';
import{GitFork,Terminal,Laptop,Cpu,ShieldCheck,BrainCircuit}from'lucide-react';

const examples=[
  {icon:Terminal,name:'Codex / coding CLI',kind:'Harness example'},
  {icon:Laptop,name:'Claude Code / agentic IDE',kind:'Harness example'},
  {icon:BrainCircuit,name:'Antigravity / IDE agents',kind:'Harness example'},
  {icon:Cpu,name:'Local or future models',kind:'Model / runtime example'},
];

export function HarnessIndependence(){return <section id="harnesses" className="py-20 md:py-28 border-t border-white/5 relative"><div className="max-w-7xl mx-auto px-4 sm:px-6">
  <div className="text-center max-w-4xl mx-auto mb-14"><div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-mono font-semibold bg-purple-500/10 text-purple-400 border border-purple-500/20 mb-4"><GitFork className="w-3.5 h-3.5"/>HARNESS & MODEL AGNOSTIC</div><h2 className="text-3xl sm:text-5xl font-black text-white tracking-tight mb-4">O protocolo não pertence à LLM.</h2><p className="text-zinc-400 text-sm sm:text-base leading-relaxed">EvoPro foi desenhado para manter memória, estado e governança fora de um fornecedor específico. Isso significa que diferentes harnesses <strong className="text-zinc-200">podem</strong> operar o protocolo quando expõem as capacidades necessárias. Não significa que todos estejam automaticamente certificados.</p></div>
  <div className="grid lg:grid-cols-[1.1fr_.9fr] gap-6"><div className="rounded-3xl bg-zinc-950 border border-zinc-800 p-6 sm:p-8"><div className="text-[10px] font-mono tracking-widest text-zinc-600 mb-6">PORTABILITY CONTRACT</div><div className="space-y-4">{[['Repository owns memory','Trocar a LLM não deve apagar contexto persistido, contratos ou decisões.'],['Capabilities are explicit','Terminal, filesystem, Git, browser, subagents e network são usados apenas quando realmente disponíveis.'],['Adapters isolate vendors','Integrações específicas devem ficar em adapters, sem transformar o Kernel em uma coleção de ifs por fornecedor.'],['Validation is empirical','Um harness só deve receber selo de compatibilidade depois de um teste real do fluxo requerido.']].map(([t,d])=><div key={t} className="p-4 rounded-2xl bg-zinc-900/50 border border-zinc-800"><h3 className="text-sm font-bold text-white mb-1">{t}</h3><p className="text-xs text-zinc-500 leading-relaxed">{d}</p></div>)}</div></div>
  <div className="rounded-3xl bg-zinc-950 border border-zinc-800 p-6 sm:p-8"><div className="text-[10px] font-mono tracking-widest text-zinc-600 mb-5">POSSIBLE EXECUTION ENGINES</div><div className="space-y-3">{examples.map(({icon:Icon,name,kind})=><div key={name} className="flex items-center gap-3 p-4 rounded-2xl bg-zinc-900/50 border border-zinc-800"><div className="w-9 h-9 rounded-xl bg-black border border-zinc-800 flex items-center justify-center"><Icon className="w-4 h-4 text-purple-400"/></div><div><div className="text-sm font-bold text-zinc-200">{name}</div><div className="text-[10px] font-mono text-zinc-600">{kind} · VALIDATE CAPABILITIES FIRST</div></div></div>)}</div><div className="mt-5 flex items-start gap-2 text-xs text-zinc-500"><ShieldCheck className="w-4 h-4 text-emerald-400 shrink-0"/><p><strong className="text-zinc-300">Estado atual:</strong> o primeiro gate end-to-end formal é o piloto do AG Menu numa IDE real. Até esse gate passar, a LP não apresenta uma matriz universal de “compatibilidade verificada”.</p></div></div></div>
</div></section>}
