'use client';

import React,{useState}from'react';
import{motion}from'framer-motion';
import{useTheme}from'@/context/ThemeContext';
import{AlertTriangle,CheckCircle2,MessageSquare,HardDrive,ArrowRight,BrainCircuit}from'lucide-react';

export function ProblemComparison(){const{theme}=useTheme();const[mode,setMode]=useState<'both'|'without'|'with'>('both');return <section id="problem" className="py-20 md:py-28 border-t border-white/5 relative"><div className="max-w-7xl mx-auto px-4 sm:px-6">
<div className="text-center max-w-4xl mx-auto mb-14"><div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-mono font-semibold bg-rose-500/10 text-rose-400 border border-rose-500/20 mb-4"><AlertTriangle className="w-3.5 h-3.5"/>THE CONTEXT PROBLEM</div><h2 className="text-3xl sm:text-5xl font-black text-white tracking-tight mb-4">Chat-native work vs.<br/><span className="bg-clip-text text-transparent" style={{backgroundImage:`linear-gradient(135deg,#fff 30%,${theme.colors.primary} 100%)`}}>repository-native cognition</span></h2><p className="text-zinc-400 text-sm sm:text-base leading-relaxed">Uma LLM pode ser excelente numa sessão e ainda não possuir memória institucional do sistema. EvoPro move contexto persistente, ownership e governança para o repositório.</p><div className="inline-flex items-center gap-1 p-1 rounded-xl bg-zinc-900 border border-zinc-800 mt-6 font-mono text-xs"><button onClick={()=>setMode('both')} className={`px-3 py-1.5 rounded-lg cursor-pointer ${mode==='both'?'bg-zinc-800 text-white':'text-zinc-400'}`}>Lado a lado</button><button onClick={()=>setMode('without')} className={`px-3 py-1.5 rounded-lg cursor-pointer ${mode==='without'?'bg-rose-950 text-rose-300':'text-zinc-400'}`}>Sem EvoPro</button><button onClick={()=>setMode('with')} className={`px-3 py-1.5 rounded-lg cursor-pointer ${mode==='with'?'bg-emerald-950 text-emerald-300':'text-zinc-400'}`}>Com EvoPro</button></div></div>
<div className="grid lg:grid-cols-2 gap-6">{(mode==='both'||mode==='without')&&<motion.article initial={{opacity:0,x:-15}} whileInView={{opacity:1,x:0}} viewport={{once:true}} className="rounded-3xl bg-zinc-950/70 border border-rose-500/20 p-6 sm:p-8"><div className="flex items-center gap-3 pb-4 mb-5 border-b border-zinc-800"><div className="w-9 h-9 rounded-xl bg-rose-500/10 border border-rose-500/25 flex items-center justify-center"><MessageSquare className="w-4 h-4 text-rose-400"/></div><div><h3 className="text-lg font-bold text-white">Chat-bound</h3><span className="text-[10px] font-mono text-rose-400">SESSION CONTEXT</span></div></div><p className="text-sm text-zinc-400 leading-relaxed mb-6">Conhecimento relevante pode ficar espalhado entre prompts, leitura ad-hoc e memória temporária da sessão. Um novo agente precisa reconstruir o cenário e pode escolher evidências diferentes.</p><div className="space-y-3 text-xs text-zinc-400">{['Decisões importantes podem desaparecer com a sessão.','Riscos e dívidas descobertos podem deixar de estar visíveis.','Cada agente pode montar um contexto diferente para a mesma tarefa.','Mudança pode ser confundida com melhoria sem baseline ou gates.'].map(x=><div key={x} className="flex gap-2"><span className="text-rose-400">✕</span>{x}</div>)}</div></motion.article>}
{(mode==='both'||mode==='with')&&<motion.article initial={{opacity:0,x:15}} whileInView={{opacity:1,x:0}} viewport={{once:true}} className="rounded-3xl bg-zinc-950/90 border border-emerald-500/25 p-6 sm:p-8"><div className="flex items-center gap-3 pb-4 mb-5 border-b border-zinc-800"><div className="w-9 h-9 rounded-xl bg-emerald-500/10 border border-emerald-500/25 flex items-center justify-center"><BrainCircuit className="w-4 h-4 text-emerald-400"/></div><div><h3 className="text-lg font-bold text-white">EvoPro Agent + repository memory</h3><span className="text-[10px] font-mono text-emerald-400">PERSISTENT COGNITIVE CONTEXT</span></div></div><p className="text-sm text-zinc-400 leading-relaxed mb-6">O agente consulta estado, memória existente, contratos, riscos, decisões e evidência do host. O Context Router seleciona o que é relevante à intenção antes da execução.</p><div className="space-y-3 text-xs text-zinc-300 mb-6">{['Detecta ou adota memória existente sem sobrescrever ownership do host.','Separa OBSERVED, INFERRED, VALIDATED e CURATED.','Roteia contexto proporcional à tarefa em vez de reler tudo.','Aplica governança, risco e validação antes de promover aprendizagem.'].map(x=><div key={x} className="flex gap-2"><CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0"/>{x}</div>)}</div><div className="p-4 rounded-xl bg-black border border-zinc-800 font-mono text-[11px] text-zinc-400 flex items-center gap-2 overflow-x-auto"><span className="text-cyan-400 font-bold">INTENT</span><ArrowRight className="w-3 h-3 shrink-0"/><span className="text-purple-400 font-bold">MEMORY</span><ArrowRight className="w-3 h-3 shrink-0"/><span className="text-amber-400 font-bold">CONTEXT</span><ArrowRight className="w-3 h-3 shrink-0"/><span className="text-emerald-400 font-bold">GOVERN</span><ArrowRight className="w-3 h-3 shrink-0"/><span className="text-white font-bold">ACT / VALIDATE</span></div><div className="mt-5 text-[11px] font-mono text-emerald-400 flex items-start gap-2"><HardDrive className="w-3.5 h-3.5 shrink-0"/><span>Objetivo: continuidade reproduzível entre sessões e harnesses. O gate de validação real ainda é o piloto AG Menu.</span></div></motion.article>}</div>
</div></section>}
