'use client';

import React,{useState} from 'react';
import {motion} from 'framer-motion';
import {useTheme} from '@/context/ThemeContext';
import {EVOPRO_CONFIG} from '@/data/evopro';
import {Play,Copy,Check,Download,BrainCircuit,MessageSquare,ShieldCheck,Terminal,ArrowRight} from 'lucide-react';

export function QuickStart(){const{theme}=useTheme();const[copied,setCopied]=useState(false);const copy=()=>{navigator.clipboard.writeText(EVOPRO_CONFIG.installCommand);setCopied(true);setTimeout(()=>setCopied(false),2000)};
const flow=[{n:'01',icon:Download,title:'Instale uma vez',copy:'Instale o EvoPro no ambiente. Este é o único passo que precisa começar como comando explícito.',detail:EVOPRO_CONFIG.installCommand},{n:'02',icon:BrainCircuit,title:'Abra o repositório na sua IDE',copy:'Use um harness com acesso ao projeto. O agente passa a trabalhar sobre o estado real do host.',detail:'Codex · Claude Code · Antigravity · IDE agents'},{n:'03',icon:MessageSquare,title:'Declare a intenção',copy:'Não memorize paths, estados internos ou sequências de CLI. Diga o que você precisa saber ou alcançar.',detail:'“Analise este repositório e determine a próxima prioridade.”'},{n:'04',icon:ShieldCheck,title:'Deixe o agente conduzir',copy:'EvoPro avalia estado, recupera memória, roteia contexto, escolhe ferramentas e propõe a próxima ação governada.',detail:'assess → context → risk → workflow → action'}];
return <section id="quickstart" className="py-20 md:py-28 border-t border-white/5 relative"><div className="max-w-7xl mx-auto px-4 sm:px-6">
<div className="text-center max-w-4xl mx-auto mb-14"><div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-mono font-semibold bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 mb-4"><Play className="w-3.5 h-3.5"/>AGENT-FIRST QUICK START</div><h2 className="text-3xl sm:text-5xl font-black text-white tracking-tight mb-4">Você não precisa aprender o EvoPro<br/><span className="text-zinc-500">para começar a usá-lo.</span></h2><p className="text-zinc-400 text-sm sm:text-base leading-relaxed max-w-3xl mx-auto">A CLI continua disponível para operadores avançados. A experiência padrão é outra: <strong className="text-zinc-200">o humano expressa intenção e o agente traduz intenção em operação do protocolo.</strong></p></div>
<div className="grid md:grid-cols-2 lg:grid-cols-4 gap-4 mb-10">{flow.map((s,i)=>{const Icon=s.icon;return <motion.article key={s.n} initial={{opacity:0,y:15}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.06}} className="relative p-5 rounded-2xl bg-zinc-950/80 border border-zinc-800"><div className="flex items-center justify-between mb-5"><span className="text-2xl font-black text-white/15 font-mono">{s.n}</span><div className="w-9 h-9 rounded-xl bg-zinc-900 border border-zinc-800 flex items-center justify-center"><Icon className="w-4 h-4" style={{color:theme.colors.primary}}/></div></div><h3 className="font-bold text-white mb-2">{s.title}</h3><p className="text-sm text-zinc-500 leading-relaxed mb-4">{s.copy}</p><div className="mt-auto pt-3 border-t border-zinc-800 text-[11px] font-mono text-zinc-400 break-words">{s.detail}</div>{i<3&&<ArrowRight className="hidden lg:block absolute -right-3 top-1/2 z-10 w-5 h-5 text-zinc-700"/>}</motion.article>})}</div>
<div className="grid lg:grid-cols-[1fr_1fr] gap-5"><div className="rounded-2xl bg-black border border-zinc-800 p-5 font-mono"><div className="flex items-center justify-between pb-3 border-b border-zinc-800 mb-4"><span className="text-[11px] text-zinc-500 flex items-center gap-2"><Terminal className="w-3.5 h-3.5"/>INSTALL</span><button onClick={copy} className="flex items-center gap-1.5 text-[11px] text-zinc-400 hover:text-white cursor-pointer">{copied?<Check className="w-3 h-3 text-emerald-400"/>:<Copy className="w-3 h-3"/>}{copied?'Copiado':'Copiar'}</button></div><div className="text-xs sm:text-sm text-zinc-300 break-all"><span className="text-emerald-400">$ </span>{EVOPRO_CONFIG.installCommand}</div></div>
<div className="rounded-2xl border border-purple-500/20 bg-purple-500/[.035] p-5"><div className="text-[10px] font-mono tracking-widest text-purple-400 mb-3">THEN TALK TO THE AGENT</div><div className="text-sm text-zinc-300"><span className="font-mono text-purple-400">you › </span>Analise este repositório e determine a próxima prioridade.</div><div className="mt-3 text-xs text-zinc-500"><span className="font-mono text-emerald-400">EvoPro › </span>O agente decide quais artefatos, comandos e verificações são necessários.</div></div></div>
<div className="mt-8 flex items-start gap-3 rounded-2xl border border-amber-500/15 bg-amber-500/[.025] p-4 text-sm text-zinc-400"><ShieldCheck className="w-4 h-4 text-amber-400 shrink-0 mt-0.5"/><p><strong className="text-zinc-200">Autonomia não significa ausência de limites.</strong> O agente opera somente dentro das capacidades do harness, dos contratos do host e das regras de governança. Decisões críticas continuam escaláveis ao humano.</p></div>
</div></section>}
