'use client';

import React,{useState} from 'react';
import {motion} from 'framer-motion';
import {ROADMAP_ITEMS} from '@/data/evopro';
import {useEvoProPublic} from '../EvoProPublicContext';
import {CheckCircle2,FlaskConical,AlertTriangle,BrainCircuit,ShieldCheck,Activity} from 'lucide-react';

export function StatusAndRoadmap(){
  const[tab,setTab]=useState<'status'|'roadmap'>('status');
  const publicState=useEvoProPublic();
  const manifest=publicState?.manifest;
  const version=manifest?.version||'0.3.1';
  const fallbackReady=['Cognitive Architecture / Second Brain V1','Existing Memory Adoption','Context Router','Agent Governance','Risk Intelligence','Semantic History','Evolution Engine','Graph Intelligence'];
  const capabilities=manifest?.capabilities||[];
  const implemented=capabilities.filter(x=>x.status==='implemented').map(x=>x.label)||fallbackReady;
  const validated=capabilities.filter(x=>x.status==='validated').map(x=>x.label);
  const observed=capabilities.filter(x=>x.status==='observed').map(x=>x.label);
  const validating=capabilities.filter(x=>x.status==='validation'||x.status==='partial').map(x=>x.label);
  const limits=manifest?.known_limitations||['Agent-first interaction is not universally production-proven across hosts and harnesses.','Harness-dependent capabilities remain UNKNOWN until exposed or declared.','Cognitive memory guides retrieval but does not replace primary evidence.'];
  const gate=manifest?.current_gate;

  return <section id="status" className="py-16 md:py-24 border-t border-white/5 relative"><div className="max-w-7xl mx-auto px-4 sm:px-6"><div className="text-center max-w-3xl mx-auto mb-12"><div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-mono font-semibold bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 mb-4"><CheckCircle2 className="w-3.5 h-3.5"/>MATURIDADE & TRANSPARÊNCIA</div><h2 className="text-3xl sm:text-5xl font-black text-white tracking-tight mb-4">Estado real, sem marketing alucinógeno.</h2><p className="text-zinc-400 text-sm sm:text-base">Implementado, observado, validado em campo e universalmente comprovado são estados diferentes. A landing lê o estado público canônico do próprio EvoPro.</p>{publicState&&<div className="mt-4 text-[10px] font-mono text-zinc-600">live source · {publicState.sourceKind}:{publicState.sourceRef} · v{version}</div>}<div className="inline-flex items-center gap-1 p-1 rounded-xl bg-zinc-900 border border-zinc-800 mt-6 font-mono text-xs"><button onClick={()=>setTab('status')} className={`px-4 py-2 rounded-lg cursor-pointer ${tab==='status'?'bg-zinc-800 text-white font-bold':'text-zinc-400'}`}>Status & Limitações</button><button onClick={()=>setTab('roadmap')} className={`px-4 py-2 rounded-lg cursor-pointer ${tab==='roadmap'?'bg-zinc-800 text-emerald-400 font-bold':'text-zinc-400'}`}>Roadmap</button></div></div>

{tab==='status'?<div className="space-y-8 font-mono text-xs">
  <div className="grid lg:grid-cols-3 gap-6">
    <div className="p-6 rounded-3xl bg-zinc-950 border border-emerald-500/30"><div className="flex items-center gap-2 text-emerald-400 font-bold text-sm pb-3 mb-4 border-b border-zinc-800"><CheckCircle2 className="w-4 h-4"/>VALIDADO EM CAMPO</div><ul className="space-y-2.5 text-zinc-300 font-sans text-xs">{validated.length?validated.map(x=><li key={x} className="flex gap-2"><span className="text-emerald-400">✓</span><span>{x}</span></li>):<li className="text-zinc-600">Nenhuma capability marcada como field-validated.</li>}</ul>{observed.length>0&&<div className="mt-5 pt-4 border-t border-zinc-800"><div className="flex items-center gap-2 text-cyan-400 font-bold text-[11px] mb-3"><Activity className="w-3.5 h-3.5"/>OBSERVADO QUALITATIVAMENTE</div><ul className="space-y-2 text-zinc-400 font-sans text-xs">{observed.map(x=><li key={x} className="flex gap-2"><span className="text-cyan-400">•</span><span>{x}</span></li>)}</ul></div>}</div>
    <div className="p-6 rounded-3xl bg-zinc-950 border border-zinc-700"><div className="flex items-center gap-2 text-zinc-300 font-bold text-sm pb-3 mb-4 border-b border-zinc-800"><BrainCircuit className="w-4 h-4"/>IMPLEMENTADO · v{version}</div><ul className="space-y-2.5 text-zinc-300 font-sans text-xs">{implemented.length?implemented.map(x=><li key={x} className="flex gap-2"><span className="text-zinc-400">✓</span><span>{x}</span></li>):fallbackReady.map(x=><li key={x} className="flex gap-2"><span className="text-zinc-500">•</span><span>{x}</span></li>)}</ul></div>
    <div className="p-6 rounded-3xl bg-zinc-950 border border-purple-500/30"><div className="flex items-center gap-2 text-purple-400 font-bold text-sm pb-3 mb-4 border-b border-zinc-800"><FlaskConical className="w-4 h-4"/>PARCIAL / PRÓXIMOS GATES</div><ul className="space-y-3 text-zinc-300 font-sans text-xs">{validating.map(x=><li key={x} className="flex gap-2"><span className="text-purple-400">⚡</span><span>{x}</span></li>)}{gate&&<li className="flex gap-2"><span className="text-cyan-400">→</span><span><strong>{gate.id}:</strong> {gate.description}</span></li>}</ul></div>
  </div>

  <div className="rounded-3xl bg-zinc-950 border border-zinc-800 p-6 sm:p-8"><div className="flex items-center gap-2 text-amber-400 font-bold text-sm pb-3 mb-4 border-b border-zinc-800"><AlertTriangle className="w-4 h-4"/>LIMITAÇÕES DECLARADAS PELO EVOPRO</div><div className="grid md:grid-cols-2 gap-4">{limits.map((desc,i)=><div key={desc} className="p-4 rounded-2xl bg-zinc-900/60 border border-zinc-800"><h4 className="font-bold text-white mb-1.5">Limitação {String(i+1).padStart(2,'0')}</h4><p className="text-[11px] text-zinc-400 font-sans leading-relaxed">{desc}</p></div>)}</div></div>
  <div className="flex gap-3 p-4 rounded-2xl border border-cyan-500/15 bg-cyan-500/[.025] text-zinc-400 font-sans"><ShieldCheck className="w-4 h-4 text-cyan-400 shrink-0"/><p><strong className="text-zinc-200">Contrato de atualização:</strong> versão, capabilities, limitações e gate atual vêm de <code className="text-cyan-300">metadata/public-manifest.json</code> no repositório EvoPro. A LP revalida essa fonte periodicamente e prefere a última tag quando disponível.</p></div>
</div>:<div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6 font-mono text-xs">{ROADMAP_ITEMS.map((item,idx)=><motion.div key={item.title} initial={{opacity:0,y:15}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:idx*.05}} className="p-6 rounded-3xl bg-zinc-950 border border-zinc-800 flex flex-col justify-between"><div><div className="flex items-center justify-between pb-3 mb-3 border-b border-zinc-800"><span className="text-[10px] text-zinc-500 uppercase tracking-widest">{item.tag}</span><span className="text-[10px] px-2 py-0.5 rounded bg-zinc-800 text-zinc-300">{item.badge}</span></div><h3 className="text-sm font-bold text-white mb-2">{item.title}</h3><p className="text-xs text-zinc-400 font-sans leading-relaxed">{item.description}</p></div><div className="pt-4 mt-6 border-t border-zinc-800 text-[10px] text-zinc-500 flex justify-between"><span>Maturidade:</span><span className="text-zinc-300 font-semibold">{item.status}</span></div></motion.div>)}</div>}</div></section>}
